import type { Metadata } from "next";
import { inter } from "./ui/fonts";
import { lusitana } from "./ui/fonts";
import "./globals.css";
import NavLinks from "./ui/default-layout/nav-links";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + 'bg-auto bg-slate-50'}>
        <div className={`absolute top-[20%] w-screen h-[72%]`}>
          {children}
        </div>

        <div className={`absolute bottom-[88%] w-screen h-[10%] text-[4vw] pl-[1vw] pb-[1vw] text-cyan-700 ${lusitana.className}`}>
          Tennessee Math Coalition
        </div>
        <div className='absolute top-[12%] left-0 right-0 w-screen h-[8%] bg-auto bg-slate-500 grid grid-cols-[7%_8%_12%_13%_52%_8%]'>
          <NavLinks></NavLinks>

          <div></div>

          <div className={`flex items-center justify-center text-[1vw] ${inter.className}`}>
            Sign Out
          </div>
        </div>

        <div className='absolute bottom-[8%] w-screen h-[0.5%] bg-auto bg-blue-900'></div>

        <div className='absolute bottom-0 w-screen h-[8%] origin-bottom bg-auto flex items-center justify-center text-cyan-500 text-[1vw]'>
          For issues or questions contact [tnmathcoalition@gmail.com]
        </div>
      </body>
    </html>
  );
}
